//
//  CPU-A
//
//  (c) 2024 TDolphin
//

#pragma once

#include <libraries/identify.h>

#undef AGNUS

namespace AOS::Identify
{
    enum class IDHW
    {
        SYSTEM = IDHW_SYSTEM,
        CPU = IDHW_CPU,
        FPU = IDHW_FPU,
        MMU = IDHW_MMU,
        OSVER = IDHW_OSVER,
        EXECVER = IDHW_EXECVER,
        WBVER = IDHW_WBVER,
        ROMSIZE = IDHW_ROMSIZE,
        CHIPSET = IDHW_CHIPSET,
        GFXSYS = IDHW_GFXSYS,
        CHIPRAM = IDHW_CHIPRAM,
        FASTRAM = IDHW_FASTRAM,
        RAM = IDHW_RAM,
        SETPATCHVER = IDHW_SETPATCHVER,
        AUDIOSYS = IDHW_AUDIOSYS,
        OSNR = IDHW_OSNR,
        VMMCHIPRAM = IDHW_VMMCHIPRAM,
        VMMFASTRAM = IDHW_VMMFASTRAM,
        VMMRAM = IDHW_VMMRAM,
        PLNCHIPRAM = IDHW_PLNCHIPRAM,
        PLNFASTRAM = IDHW_PLNFASTRAM,
        PLNRAM = IDHW_PLNRAM,
        VBR = IDHW_VBR,
        LASTALERT = IDHW_LASTALERT,
        VBLANKFREQ = IDHW_VBLANKFREQ,
        POWERFREQ = IDHW_POWERFREQ,
        ECLOCK = IDHW_ECLOCK,
        SLOWRAM = IDHW_SLOWRAM,
        GARY = IDHW_GARY,
        RAMSEY = IDHW_RAMSEY,
        BATTCLOCK = IDHW_BATTCLOCK,
        CHUNKYPLANAR = IDHW_CHUNKYPLANAR,
        POWERPC = IDHW_POWERPC,
        PPCCLOCK = IDHW_PPCCLOCK,
        CPUREV = IDHW_CPUREV,
        CPUCLOCK = IDHW_CPUCLOCK,
        FPUCLOCK = IDHW_FPUCLOCK,
        RAMACCESS = IDHW_RAMACCESS,
        RAMWIDTH = IDHW_RAMWIDTH,
        RAMCAS = IDHW_RAMCAS,
        RAMBANDWIDTH = IDHW_RAMBANDWIDTH,
        TCPIP = IDHW_TCPIP,
        PPCOS = IDHW_PPCOS,
        AGNUS = IDHW_AGNUS,
        AGNUSMODE = IDHW_AGNUSMODE,
        DENISE = IDHW_DENISE,
        DENISEREV = IDHW_DENISEREV,
        BOINGBAG = IDHW_BOINGBAG,
        EMULATED = IDHW_EMULATED,
        XLVERSION = IDHW_XLVERSION,
        HOSTOS = IDHW_HOSTOS,
        HOSTVERS = IDHW_HOSTVERS,
        HOSTMACHINE = IDHW_HOSTMACHINE,
        HOSTCPU = IDHW_HOSTCPU,
        HOSTSPEED = IDHW_HOSTSPEED,
        LASTALERTTASK = IDHW_LASTALERTTASK,
        PAULA = IDHW_PAULA,
        ROMVER = IDHW_ROMVER,
        RTC = IDHW_RTC,
        NUMBEROF = IDHW_NUMBEROF,
    };
}
